In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("globalAirQuality.csv")

In [11]:
#single condition query
df.query("aqi>100")[["city","aqi"]]

           city  aqi
0      New York  108
3      New York  158
6      New York  155
7      New York  115
8      New York  121
...         ...  ...
17991    Zurich  104
17993    Zurich  153
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122

[9721 rows x 2 columns]

In [12]:
#multiple condition query
df.query("aqi>100 & temperature<25")[["city","temperature","aqi"]]

           city  temperature  aqi
0      New York       18.504  108
3      New York       23.140  158
8      New York       24.092  121
12     New York       14.584  114
16     New York        7.884  130
...         ...          ...  ...
17987    Zurich       16.741  118
17988    Zurich       13.982  122
17993    Zurich       20.437  153
17995    Zurich        7.079  103
17997    Zurich       21.951  122

[5869 rows x 3 columns]

In [13]:
#use of python variable
max_aqi=100
df.query("aqi>100")[["city","temperature"]]

           city  temperature
0      New York       18.504
3      New York       23.140
6      New York       36.729
7      New York       37.891
8      New York       24.092
...         ...          ...
17991    Zurich       32.556
17993    Zurich       20.437
17995    Zurich        7.079
17996    Zurich       28.734
17997    Zurich       21.951

[9721 rows x 2 columns]

In [14]:
#query creates copy of the filtered data....
aqi_data=df.query("aqi>100")[["city","temperature"]]
aqi_data

           city  temperature
0      New York       18.504
3      New York       23.140
6      New York       36.729
7      New York       37.891
8      New York       24.092
...         ...          ...
17991    Zurich       32.556
17993    Zurich       20.437
17995    Zurich        7.079
17996    Zurich       28.734
17997    Zurich       21.951

[9721 rows x 2 columns]