In [5]:
import pandas as pd

In [6]:
df=pd.read_csv("raw_data.csv")

### Handle missing values

In [7]:
df.isnull()

       id   name    age  country  gender  income
0   False  False  False    False   False   False
1   False  False  False    False   False   False
2   False  False   True    False   False   False
3   False  False   True    False   False   False
4   False  False  False    False   False    True
5   False  False  False    False   False   False
6   False   True  False    False   False   False
7   False  False  False     True   False   False
8   False  False  False    False   False   False
9   False  False   True    False   False   False
10  False  False  False    False    True   False

In [8]:
df.isnull().sum()

id         0
name       1
age        3
country    1
gender     1
income     1
dtype: int64

In [9]:
df.dropna() #row drop ....
df.dropna(axis=1) #column drop.....

    id
0    1
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10

In [10]:
df.fillna(0)
age_mean=df["age"].mean()
df["age"].fillna(age_mean)
cleaned_data=df.copy()
cleaned_data["age"] = cleaned_data["age"].fillna(age_mean)
cleaned_data

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female      NaN
5    5        Li Wei  27.00   China     Male  51000.0
6    6           NaN  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     NaN     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

In [11]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [12]:
# forward fill ........
df.ffill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  29.0  Canada   Female  62000.0
3    3          Alex  29.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  47000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6        Li Wei  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0   India     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  29.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA     Male  58000.0

In [13]:
df.bfill() #backword filling......

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

### Handle Duplicates

In [14]:
df.duplicated() #overall duplicates
df["country"].duplicated() #columns duplicates
df[["country","gender"]].duplicated() # set of attributes duplicates

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [15]:
df.drop_duplicates() # to drop row wise duplicates
df2=df.copy()
df.drop_duplicates(inplace=True) # for making the change in this data (like index)

### Handle data type

In [16]:
df.dtypes #returns data type of each columns..
df["name"].dtypes # return that particular columns data type......
# changing data type fo any columns
df2=df.copy()
df2=df2.fillna(0)
df2["aga"]=df2["age"].astype("int64").copy()
df2.dtypes

#changing to date_time data type..
aqi_data=pd.read_csv("globalAirQuality.csv")
aqi_data["timestamp"]=pd.to_datetime(aqi_data["timestamp"])
aqi_data["timestamp"].dtype

date_str=pd.Series([pd.to_datetime("2026-12-31")])
date_str.dtype

dtype('<M8[us]')

### Handle strings

In [17]:
#.str.lower(), str.upper(), str.capitalize()
str="nAme"
str.lower()
str.upper
str.capitalize()

'Name'

In [18]:
df.ffill()
df["gender"].str.lower()
df["gender"].str.upper()
df["gender"].str.capitalize()

0        Male
2      Female
3     Unknown
4      Female
5        Male
6      Female
7        Male
8      Female
9        Male
10        NaN
Name: gender, dtype: str

In [19]:
#strip() ->used to remove extra spaces
str2="  name pradip"
print(str2)

  name pradip

In [20]:
str2.strip()

'name pradip'

In [30]:
#split string on the basis of (,, spaces,any letter, any symbol)
str3="Pradip Yadav is, a good @ guy" 
str3.split(",")
str3.split(" ")
df["name"].str.split(" ")

0         [John, Doe]
2       [Jane, Smith]
3              [Alex]
4     [Maria, Garcia]
5           [Li, Wei]
6                 NaN
7       [Ahmed, Khan]
8       [Rachel, Lee]
9      [Carlos, Ruiz]
10     [Emily, Davis]
Name: name, dtype: object

In [33]:
#to check if it contains or not 
df["country"].str.contains("INDIA")
df["country"].str.contains("US")

0      True
2     False
3      True
4     False
5     False
6     False
7     False
8      True
9     False
10     True
Name: country, dtype: bool

In [36]:
#to ignore upper or lower case.....
df["country"].str.contains("india", case=False)

0     False
2     False
3     False
4     False
5     False
6      True
7     False
8     False
9     False
10    False
Name: country, dtype: bool