## DAta Transformation..

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("employee_data.csv")

In [4]:
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [21]:
### .apply(function)
df2=df.copy()
df2["tax"]=df2["Salary"].apply(lambda x: "20%" if x>=50000 else "10%")
df2

   ID     Name  Age Department  Salary  tax
0   1    Alice   25         HR   55000  20%
1   2      Bob   32         IT   72000  20%
2   3  Charlie   28    Finance   48000  10%
3   4    David   45  Marketing   91000  20%
4   5      Eva   38         IT   65000  20%
5   6    Frank   29    Finance   50000  20%
6   7    Grace   41         HR   82000  20%
7   8   Hannah   26  Marketing   47000  10%
8   9      Ian   35         IT   75000  20%
9  10    Julia   30    Finance   60000  20%

In [24]:
### .map ()

In [31]:
df3=pd.read_csv("raw_data.csv")
gender_map={
    "Male" : "M",
    "Female" : "F",
    "Unknown" : "U"
    }
df3["gender"]=df3["gender"].map(gender_map)
df3

    id          name   age country gender   income
0    1      John Doe  29.0     USA      M  55000.0
1    1      John Doe  29.0     USA      M  55000.0
2    2    Jane Smith   NaN  Canada      F  62000.0
3    3          Alex   NaN     USA      U  47000.0
4    4  Maria Garcia  34.0   Spain      F      NaN
5    5        Li Wei  27.0   China      M  51000.0
6    6           NaN  45.0   India      F  73000.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0
8    8    Rachel Lee  29.0     USA      F  62000.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0
10  10   Emily Davis  31.0     USA    NaN  58000.0

In [32]:
### .assign()

In [33]:
df3.assign(new_income=df3["income"]*1.1)

    id          name   age country gender   income  new_income
0    1      John Doe  29.0     USA      M  55000.0     60500.0
1    1      John Doe  29.0     USA      M  55000.0     60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0     68200.0
3    3          Alex   NaN     USA      U  47000.0     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN         NaN
5    5        Li Wei  27.0   China      M  51000.0     56100.0
6    6           NaN  45.0   India      F  73000.0     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0     74800.0
8    8    Rachel Lee  29.0     USA      F  62000.0     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0     49500.0
10  10   Emily Davis  31.0     USA    NaN  58000.0     63800.0

In [38]:
df3["country"]=df3["country"].replace("USA", "US")
df3

    id          name   age country gender   income
0    1      John Doe  29.0      US      M  55000.0
1    1      John Doe  29.0      US      M  55000.0
2    2    Jane Smith   NaN  Canada      F  62000.0
3    3          Alex   NaN      US      U  47000.0
4    4  Maria Garcia  34.0   Spain      F      NaN
5    5        Li Wei  27.0   China      M  51000.0
6    6           NaN  45.0   India      F  73000.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0
8    8    Rachel Lee  29.0      US      F  62000.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0
10  10   Emily Davis  31.0      US    NaN  58000.0

In [46]:
### rename function 
df3.columns=["Id","Name","Age","Country","Gender","Income"]
df3.rename(columns={"Income":"Salary"})
df3.rename(index={1:"First"})

       Id          Name   Age Country Gender   Income
0       1      John Doe  29.0      US      M  55000.0
First   1      John Doe  29.0      US      M  55000.0
2       2    Jane Smith   NaN  Canada      F  62000.0
3       3          Alex   NaN      US      U  47000.0
4       4  Maria Garcia  34.0   Spain      F      NaN
5       5        Li Wei  27.0   China      M  51000.0
6       6           NaN  45.0   India      F  73000.0
7       7    Ahmed Khan  38.0     NaN      M  68000.0
8       8    Rachel Lee  29.0      US      F  62000.0
9       9   Carlos Ruiz   NaN  Mexico      M  45000.0
10     10   Emily Davis  31.0      US    NaN  58000.0

In [57]:
sorted_df=df3.sort_values(["Income"]) #for sorting on the basis of single parimeter
sorted_df=df3.sort_values(["Income","Age"])# for sorting on the basis of multiple parimeter
sorted_df=df3.sort_values(["Income"], ascending=False)
sorted_df
# sorted_df.sort_index() #sort according to index (reverte the changes)
# # sorted_df.reset_index() # sort the index by creating new index 
# sorted_df.reset_index(drop=True) # same as above but in this the older index will not be preserved, it will be droped(deleted)

    Id          Name   Age Country Gender   Income
6    6           NaN  45.0   India      F  73000.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0
8    8    Rachel Lee  29.0      US      F  62000.0
2    2    Jane Smith   NaN  Canada      F  62000.0
10  10   Emily Davis  31.0      US    NaN  58000.0
0    1      John Doe  29.0      US      M  55000.0
1    1      John Doe  29.0      US      M  55000.0
5    5        Li Wei  27.0   China      M  51000.0
3    3          Alex   NaN      US      U  47000.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0
4    4  Maria Garcia  34.0   Spain      F      NaN

In [69]:
## RANKING OF DATA
sorted_df.fillna(50)
sorted_df["Ranking"]=df["Salary"].rank(ascending=False, method="dense")
sorted_df

    Id          Name   Age Country Gender   Income  Ranking
6    6           NaN  45.0   India      F  73000.0      2.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0     10.0
8    8    Rachel Lee  29.0      US      F  62000.0      3.0
2    2    Jane Smith   NaN  Canada      F  62000.0      9.0
10  10   Emily Davis  31.0      US    NaN  58000.0      NaN
0    1      John Doe  29.0      US      M  55000.0      7.0
1    1      John Doe  29.0      US      M  55000.0      4.0
5    5        Li Wei  27.0   China      M  51000.0      8.0
3    3          Alex   NaN      US      U  47000.0      1.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0      6.0
4    4  Maria Garcia  34.0   Spain      F      NaN      5.0

In [74]:
## Reorder columns
sorted_df[["Id","Name", "Age", "Gender", "Income", "Ranking", "Country"]]

    Id          Name   Age Gender   Income  Ranking Country
6    6           NaN  45.0      F  73000.0      2.0   India
7    7    Ahmed Khan  38.0      M  68000.0     10.0     NaN
8    8    Rachel Lee  29.0      F  62000.0      3.0      US
2    2    Jane Smith   NaN      F  62000.0      9.0  Canada
10  10   Emily Davis  31.0    NaN  58000.0      NaN      US
0    1      John Doe  29.0      M  55000.0      7.0      US
1    1      John Doe  29.0      M  55000.0      4.0      US
5    5        Li Wei  27.0      M  51000.0      8.0   China
3    3          Alex   NaN      U  47000.0      1.0      US
9    9   Carlos Ruiz   NaN      M  45000.0      6.0  Mexico
4    4  Maria Garcia  34.0      F      NaN      5.0   Spain