# Grouping and Aggregation of data

In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("raw_data.csv")

In [11]:
df.groupby("country")["income"].mean()
df.groupby("country")["income"].sum()
df.groupby("country")["income"].min()
df.groupby("country")["income"].max()

country
Canada    62000.0
China     51000.0
India     73000.0
Mexico    45000.0
Spain         NaN
USA       62000.0
Name: income, dtype: float64

In [14]:
df.groupby("gender")["income"].mean()
df.groupby("gender")["income"].sum()
df.groupby("gender")["income"].min()
df.groupby("gender")["income"].max()

gender
Female     73000.0
Male       68000.0
Unknown    47000.0
Name: income, dtype: float64

In [17]:
### aggregate  function 
df.groupby("country")["income"].agg(["mean","sum","min","max"])
df.groupby("country")["income"].aggregate(avg_salary="mean",sum_salary="sum", min_salary="min", max_salary="max")

         avg_salary  sum_salary  min_salary  max_salary
country
Canada      62000.0     62000.0     62000.0     62000.0
China       51000.0     51000.0     51000.0     51000.0
India       73000.0     73000.0     73000.0     73000.0
Mexico      45000.0     45000.0     45000.0     45000.0
Spain           NaN         0.0         NaN         NaN
USA         55400.0    277000.0     47000.0     62000.0

In [18]:
df.groupby("country").agg({
    "income" : "mean",
    "age" : "mean"
})

          income   age
country
Canada   62000.0   NaN
China    51000.0  27.0
India    73000.0  45.0
Mexico   45000.0   NaN
Spain        NaN  34.0
USA      55400.0  29.5

In [19]:
df.groupby("country").agg(
    avg_salary=("income","mean"),
    avg_age=("age","mean")
)

         avg_salary  avg_age
country
Canada      62000.0      NaN
China       51000.0     27.0
India       73000.0     45.0
Mexico      45000.0      NaN
Spain           NaN     34.0
USA         55400.0     29.5