# Melt and pivote functions of pandas

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("raw_data.csv")

In [3]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

### Melt function => use to convert Wide to long formate

In [30]:
melted_df=df.melt(
    id_vars=["id", "name", "country", "gender"],
    value_vars=["age", "income"],
    var_name="variable",
    value_name="value"
)
melted_df

    id          name country   gender variable    value
0    1      John Doe     USA     Male      age     29.0
1    1      John Doe     USA     Male      age     29.0
2    2    Jane Smith  Canada   Female      age      NaN
3    3          Alex     USA  Unknown      age      NaN
4    4  Maria Garcia   Spain   Female      age     34.0
5    5        Li Wei   China     Male      age     27.0
6    6           NaN   India   Female      age     45.0
7    7    Ahmed Khan     NaN     Male      age     38.0
8    8    Rachel Lee     USA   Female      age     29.0
9    9   Carlos Ruiz  Mexico     Male      age      NaN
10  10   Emily Davis     USA      NaN      age     31.0
11   1      John Doe     USA     Male   income  55000.0
12   1      John Doe     USA     Male   income  55000.0
13   2    Jane Smith  Canada   Female   income  62000.0
14   3          Alex     USA  Unknown   income  47000.0
15   4  Maria Garcia   Spain   Female   income      NaN
16   5        Li Wei   China     Male   income  51000.0
17   6           NaN   India   Female   income  73000.0
18   7    Ahmed Khan     NaN     Male   income  68000.0
19   8    Rachel Lee     USA   Female   income  62000.0
20   9   Carlos Ruiz  Mexico     Male   income  45000.0
21  10   Emily Davis     USA      NaN   income  58000.0

### Pivote function => use to convert Long to Wide formate

In [29]:
# Remove dupicates before applying pivote 

melted_df=melted_df.drop_duplicates(
    subset=["id", "name", "country", "gender", "variable"]
)

melted_df.duplicated(
    subset=["id", "name", "country", "gender", "variable"]
).sum()

pivoted_df = melted_df.pivot(
    index=["id", "name", "country", "gender"],
    columns="variable",
    values="value"
)
pivoted_df

variable                          age   income
id name         country gender
1  John Doe     USA     Male     29.0  55000.0
2  Jane Smith   Canada  Female    NaN  62000.0
3  Alex         USA     Unknown   NaN  47000.0
4  Maria Garcia Spain   Female   34.0      NaN
5  Li Wei       China   Male     27.0  51000.0
6  nan          India   Female   45.0  73000.0
7  Ahmed Khan   nan     Male     38.0  68000.0
8  Rachel Lee   USA     Female   29.0  62000.0
9  Carlos Ruiz  Mexico  Male      NaN  45000.0
10 Emily Davis  USA     nan      31.0  58000.0