# Merge and join data

In [6]:
import pandas as pd

In [7]:
customer_df=pd.DataFrame(
    {
        "customer_id":[1,2,3,4],
        "name":["Adam", "Bob","Charlie", "Dave"]
    }
)

In [9]:
order_df=pd.DataFrame({
    "order_id":[101,102,103,104],
    "customer_id":[2,1,4,5],
    "amount":[250,120,300,180]
})

In [11]:
# inner join (in this the data common in both table will be add to the new table)
pd.merge(customer_df, order_df, on="customer_id", how="inner")  # default inner

   customer_id  name  order_id  amount
0            1  Adam       102     120
1            2   Bob       101     250
2            4  Dave       103     300

In [13]:
# left join (in this the data common and all data in first table will be added to the new table)
pd.merge(customer_df, order_df, on="customer_id" ,how="left")

   customer_id     name  order_id  amount
0            1     Adam     102.0   120.0
1            2      Bob     101.0   250.0
2            3  Charlie       NaN     NaN
3            4     Dave     103.0   300.0

In [14]:
# right join (in this the data common and all data in second table will be added to the new table)
pd.merge(customer_df, order_df, on="customer_id" ,how="right")

   customer_id  name  order_id  amount
0            2   Bob       101     250
1            1  Adam       102     120
2            4  Dave       103     300
3            5   NaN       104     180

In [15]:
# outer join (in this the uinon of both the table is sored in the new table)
pd.merge(customer_df, order_df, on="customer_id" ,how="outer")

   customer_id     name  order_id  amount
0            1     Adam     102.0   120.0
1            2      Bob     101.0   250.0
2            3  Charlie       NaN     NaN
3            4     Dave     103.0   300.0
4            5      NaN     104.0   180.0