In [1]:
import pandas as pd

In [2]:
df1=pd.DataFrame({
    "Roll_number":[1,2,3,4,5],
    "name":["Pradip","Aditya","Satish","Ayush","Piyush"]
})

In [4]:
df2=pd.DataFrame({
    "Roll_number":[6,7,8,9,10],
    "name":["Anish","Rudra","Satyendra","Durgesh","Amarjeet"]
})

In [19]:
df3=pd.concat([df1,df2]) # row 
# to ignore the preserved index 
df3=pd.concat([df1,df2],ignore_index=True)
df3

   Roll_number       name
0            1     Pradip
1            2     Aditya
2            3     Satish
3            4      Ayush
4            5     Piyush
5            6      Anish
6            7      Rudra
7            8  Satyendra
8            9    Durgesh
9           10   Amarjeet

In [22]:
df4=pd.concat([df1,df2], axis=1) # column
df4

   Roll_number    name  Roll_number       name
0            1  Pradip            6      Anish
1            2  Aditya            7      Rudra
2            3  Satish            8  Satyendra
3            4   Ayush            9    Durgesh
4            5  Piyush           10   Amarjeet